server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product
          uri: http://product-service
          predicates:
            - Path=/products/**
        - id: order
          uri: http://order-service
          predicates:
            - Path=/orders/**
        - id: user
          uri: http://user-service
          predicates:
            - Path=/users/**
